server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-microservice
          uri: lb://auth-microservice
          predicates[0]:
            - Path=/generate-token
          predicates[1]:
            - Path=/api/v1/users/**
          predicates[2]:
            - Path=/roles/**
          filters[0]: AuthFilter  
              