server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-microservice
        uri: lb://auth-microservice
        pridicates:
          - Path=/generate-token
          - Path=/api/v1/users/**
          - Path=/roles/**  