server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url:
      default-zone: http://localhost:8761/eureka/
      instance:
        hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_microservice
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   