server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone:  http://192.168.1.171/eureka-microservice
      instance:
        hostname: 192.168.1.171
  instance:
    instance-id: ${spring.application.name}:${random.uuid}        

spring:
  datasource:
    url: jdbc:mysql://192.168.1.171:3306/auth-microservice
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   