server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    eureka-server-u-r-l-context: http://192.168.1.34:8761/eureka
  instance:
    hostname: localhost  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-microservice
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   