server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/auth-microservice
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true   

jwt:
  secret: electrohogar